version: '3'


services:
  gitea:
    build:
      context: ./gitea
    restart: always
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"

volumes:
  data:
  config:
